# Generated by Django 5.2.4 on 2025-08-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10, verbose_name="狀態名稱")),
            ],
            options={
                "verbose_name": "狀態名稱",
                "verbose_name_plural": "狀態名稱",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20, verbose_name="職位名稱")),
                ("company", models.CharField(max_length=20, verbose_name="公司名稱")),
                ("content", models.TextField(verbose_name="內容")),
                ("job_link", models.URLField(verbose_name="職位頁面")),
                ("company_link", models.URLField(verbose_name="公司官網")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="使用者",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="job_track.jobstatus",
                        verbose_name="狀態",
                    ),
                ),
            ],
            options={
                "verbose_name": "求職紀錄",
                "verbose_name_plural": "求職紀錄",
                "ordering": ["-created_at"],
            },
        ),
    ]
