# Generated by Django 5.2.4 on 2025-08-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job_track", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ["-applied_at"],
                "verbose_name": "求職紀錄",
                "verbose_name_plural": "求職紀錄",
            },
        ),
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="job",
            name="applied_at",
            field=models.DateField(blank=True, null=True, verbose_name="投遞時間"),
        ),
    ]
